### ISSUE TITLE
How to create a patch

### ISSUE THREAD

**Issue by cedricve** [buildroot/buildroot#12]
Hello

I was wondering how I can create a patch. I'm currently create a package for kerberos.io, but it's unclear for me, how a patch can be created/generated.

Regards

**Comment by tpetazzoni** [comment]
Please read the Buildroot documentation at http://buildroot.org/downloads/manual/manual.html, which explains in details how to contribute. See especially the section https://buildroot.org/downloads/manual/manual.html#submitting-patches. Thanks!

**Comment by cedricve** [comment]
Perfect! That worked.

`$ git format-patch -M -n -s -o outgoing origin/master`
