### ISSUE TITLE
latest on July 1st, system from raspberrypi3_defconfig no device wlan0 for wifi

### ISSUE THREAD

**Issue by Tibalt** [buildroot/buildroot#16]
I do not know if somebody has suffered the same problem. 
I tried the defconfig for rasp3. The sdcard.img generated by buildroot is running well except that wlan0 is not in the system. Then I tried to fix it by compilation with BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_MDEV=y, but still did not work.

**Comment by tpetazzoni** [comment]
Thanks for your report, but this Github repository is not the official Buildroot repository, and we do not use Github's issue tracker. Please report Buildroot issues either on the Buildroot mailing list, or to the Buildroot's bug tracker. Thanks!
