### ISSUE TITLE
Main site down

### ISSUE THREAD

**Issue by pgeremia** [buildroot/buildroot#17]
I cannot reach the main build root site.  There are some specific versions I have been relying on.  Is there an ETA as to when it will be back?

I am only creating this ticket here because I see no other way to communicate with the owners.

@tpetazzoni

**Comment by MrAda** [comment]
Thanks for being the first to mention this.  I have been wondering myself about the site as I am trying to use build root for first time and the final sdcard.img doesn't seem to work for me.

**Comment by cia48621793** [comment]
What on earth will ever attack the innocent Buildroot?

**Comment by MrAda** [comment]
I am confused. Why am i getting all kinds of mesages from users working on git.buildroot.net when I cannot access the site.  Is it up or down?  I still cannot build a R-pi3 root.

**Comment by cia48621793** [comment]
@MrAda Someone viciously attacked Buildroot's website

**Comment by warpcoil** [comment]
That's terrible, I've been trying to get to the buildroot website for two days now.  These people are idiots and that's putting it politely.

**Comment by warpcoil** [comment]
Anyone have more info? IPs and whatnot . . . anyone investigating?

**Comment by tpetazzoni** [comment]
The OSUOSL guys, who are hosting the Buildroot website and other facilities, are working on the topic. Whenever they bring up the website, they get DDoS again, so they are going to move it to a different location, where they have more filtering capabilities.

**Comment by warpcoil** [comment]
Thank you @tpetazzoni, I hope they launch some sort of investigation, I for one would definitely not stand for that.  These people should be brought down.  It makes me so angry . . .

**Comment by warpcoil** [comment]
And kudos to OSU for providing such a wonderful resource . . .

**Comment by MrAda** [comment]
@tpetazzoni I am confused by all of the emails I am getting from "buildroot@buildroot.org".  Did the hacker completely wipe out the software?  Does have to be rebuilt from scratch?  When will this site get all of the current updates?

I am still stuck on not getting any response from my RPi3.  Do I have to use HDMI source to see anything?  My LCD (the offical one for RPi) is just showing its color box and that's it.  Do I need more drivers?

**Comment by cia48621793** [comment]
Have mercy for Buildroot, attackers: Why do you even bother to touch an FOSS project? Go touch Windows or Microsoft instead.

**Comment by tpetazzoni** [comment]
@MrAda we have not been hacked. We are only the subject of a DDoS attack, which makes the Web service unavailable. However, other services (Git repository, mailing list) are operational, so the development continues as normal.

**Comment by MrAda** [comment]
@tpetazzoni, I see we are up and running on buildroot main site again.  That is a good thing.  I did notice a lot of development activity still on the mailing list.  Is there a version that is stable enough to use for RPi 3?  I am stuck otherwise.

**Comment by tpetazzoni** [comment]
The main site is back up.

**Comment by pgeremia** [comment]
Thanks you for letting us know!  Great news!
