### ISSUE TITLE
Any one use buildroot to cross-compile Hadoop?

### ISSUE THREAD

**Issue by yadzhang** [buildroot/buildroot#18]
I want to cross compile hadoop on my own ubuntu vm(x86_64) for powerpc 64le. I have searched the method for a long time on the web,  but I don't know how to use buildroot for crossing-compile.  Some native libraries of Hadoop was written by language C. I just replace gcc and g++ with powerpc64le-linux-gcc and powerpc64le-linux-g++, but it faied with ant make failed. 

Any one has tried cross-compile hadoop? 
And can any one tell me how to compile my own project in buildroot?

I use buildroot-2015-05, and why I can not see cmake in output/host/usr/bin? How can I add cmake to buildroot, and I have see cmake config in package?

**Comment by tpetazzoni** [comment]
Please do not use Github's issue tracker for Buildroot issues. This Github repository is only a mirror. Please ask questions either on the Buildroot mailing list, on the Buildroot bug tracker, or on the Buildroot IRC channel.
