### ISSUE TITLE
Odroid-C2 buildroot does not work

### ISSUE THREAD

**Issue by gahabana** [buildroot/buildroot#21]
Hi, 
i followed instructions to the letter from https://github.com/buildroot/buildroot/tree/master/board/hardkernel/odroidc2
Result burned to SD-Card and when i turn it on, nothing happens - bluelight doesn't even blink just stays on meaning linux kernel hasn't really loaded. 
Could ANYone confirm it works for them ?

tx

**Comment by paralin** [comment]
Check http://github.com/paralin/SkiffOS for a guaranteed working C2 distribution built on Buildroot.

Also, don't report issues here, use the mailing list. You should close this one.

**Comment by gahabana** [comment]
hi @paralin i will close it, have looked at SkiffOS and thing it's awesome model for those who are more into microservices ... i was looking to harden/simplify appliance build for one purpose (audio player) with some basic customizations (3 different players  o/w only one is running, mini webserver to choose one of the three) ... i could tinker with putting 'squeezelite' in docker, probably could do the same with non-open source 'roon endpoint' and of course with 'mpd' ... and i think buildroot bit closer in philosphy plus im slow in learning new things.
Will close the 'issue' . I did seek support on buildroot IRC since there are no forums as well as on mailing list. Seems like noone is testing builds, at least not on Odroid.
Thanks anyhow !

**Comment by paralin** [comment]
@gahabana you can remove Docker from the image extremely easily, at the lowest level the `odroid/c2` config produces a baseline working OS with networking, wifi, and an ssh server (no docker)

**Comment by gahabana** [comment]
@paralin huh, okey ... you got me thinking, might give it a try ! 
wish someone as smart as you had time to look at why buildroot ain't working (and i did try latest u-boot and kernel as well) ... really appreciate your response !
