### ISSUE TITLE
mplayer xorg development files from host

### ISSUE THREAD

**Issue by glscantlen** [buildroot/buildroot#4]
I am using buildroot-2015.05
Installed on a fresh Ubuntu 14.04 host, with only basic build requirements ie 
"apt-get install build-essential git ccache"

I have configured BuildRoot for basic Xorg with mplayer. (I'll attach defconfig)
The "make" passes without error and everything works on target H/W except mplayer.
Mplayer acts as-if there is no xorg.
I have discovered, if I "apt-get install xorg-dev" to the host and rebuild mplayer it will then work.
Why is mplayer's configure using the host's xorg-development files? I would expect it must use the BuildRoot tree's development files.

sorry I can not attach a simple text file... DAH!
So I'll just paste here:

BR2_arm=y
BR2_cortex_a7=y
BR2_ARM_EABIHF=y
BR2_DEFCONFIG="$(CONFIG_DIR)/defconfig"
BR2_CCACHE=y
BR2_TOOLCHAIN_EXTERNAL=y
BR2_TOOLCHAIN_EXTERNAL_CUSTOM=y
BR2_TOOLCHAIN_EXTERNAL_PATH="$(HOME)/xu3_mplayer/linaro-4.9"
BR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX="arm-linux-gnueabihf"
BR2_TOOLCHAIN_EXTERNAL_HEADERS_3_17=y
BR2_TOOLCHAIN_EXTERNAL_CUSTOM_GLIBC=y
BR2_TOOLCHAIN_EXTERNAL_CXX=y
BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_EUDEV=y
BR2_ROOTFS_POST_BUILD_SCRIPT="support/scripts/config_eth"
BR2_PACKAGE_ALSA_UTILS=y
BR2_PACKAGE_ALSA_UTILS_SPEAKER_TEST=y
BR2_PACKAGE_FFMPEG=y
BR2_PACKAGE_MPLAYER=y
BR2_PACKAGE_MESA3D_DEMOS=y
BR2_PACKAGE_MESA3D=y
BR2_PACKAGE_MESA3D_DRI_DRIVER_SWRAST=y
BR2_PACKAGE_MESA3D_OPENGL_EGL=y
BR2_PACKAGE_MESA3D_OPENGL_ES=y
BR2_PACKAGE_XORG7=y
BR2_PACKAGE_XSERVER_XORG_SERVER=y
BR2_PACKAGE_XSERVER_XORG_SERVER_MODULAR=y
BR2_PACKAGE_XSERVER_XORG_SERVER_AIGLX=y
BR2_PACKAGE_XAPP_TWM=y
BR2_PACKAGE_XAPP_XCLOCK=y
BR2_PACKAGE_XDRIVER_XF86_INPUT_EVDEV=y
BR2_PACKAGE_XDRIVER_XF86_INPUT_KEYBOARD=y
BR2_PACKAGE_XDRIVER_XF86_INPUT_MOUSE=y
BR2_PACKAGE_XDRIVER_XF86_VIDEO_ARMSOC=y
BR2_PACKAGE_XDRIVER_XF86_VIDEO_FBDEV=y
BR2_PACKAGE_XTERM=y
BR2_PACKAGE_PYTHON=y
BR2_PACKAGE_PYTHON_BZIP2=y
BR2_PACKAGE_PYTHON_READLINE=y
BR2_PACKAGE_PYTHON_SSL=y
BR2_PACKAGE_PYTHON_PYEXPAT=y
BR2_PACKAGE_PYTHON_ZLIB=y
BR2_PACKAGE_LIBDRI2=y
BR2_PACKAGE_LIBDRM_EXYNOS=y
BR2_PACKAGE_LIBGLEW=y
BR2_PACKAGE_LIBGLU=y
BR2_PACKAGE_WAYLAND=y
BR2_PACKAGE_OPENSSH=y
BR2_PACKAGE_RSYNC=y

**Comment by tpetazzoni** [comment]
Thanks for the report. However, as explained on the Buildroot Github page, this is not where the Buildroot development takes place. Could you report your bug to the Buildroot bug tracker, or to the Buildroot mailing list?

Thanks!

**Comment by glscantlen** [comment]
sorry. did not see that.
It has now been submitted on bugzilla
