### ISSUE TITLE
Error when running make linux-menuconfig

### ISSUE THREAD

**Issue by chfakht** [buildroot/buildroot#7]
I have done 
make raspberrypi_defconfig
make menu-config
make linux-menuconfig
i got :
PATH="/home/larbi/PFA/rootBuild/buildroot/output/host/bin:/home/larbi/PFA/rootBuild/buildroot/output/host/sbin:/home/larbi/PFA/rootBuild/buildroot/output/host/usr/bin:/home/larbi/PFA/rootBuild/buildroot/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:   /usr/local/games" BR_BINARIES_DIR=/home/larbi/PFA/rootBuild/buildroot/output/images /usr/bin/make -j5 -C /home/larbi/PFA/rootBuild/buildroot/output/build/linux-592503752b6951972f161f04280683c5af38d173 HOSTCC="/usr/bin/gcc" HOSTCFLAGS="" ARCH=arm INSTALL_MOD_PATH=/home/larbi/PFA/rootBuild/buildroot/output/target CROSS_COMPILE="/home/larbi/PFA/rootBuild/buildroot/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-" DEPMOD=/home/larbi/PFA/rootBuild/buildroot/output/host/sbin/depmod bcmrpi_defconfig
make: *** /home/larbi/PFA/rootBuild/buildroot/output/build/linux-592503752b6951972f161f04280683c5af38d173: No such file or directory.  Stop.
make[1]: *** [/home/larbi/PFA/rootBuild/buildroot/output/build/linux-592503752b6951972f161f04280683c5af38d173/.config] Error 2
make: *** [_all] Error 2

what's wrong ? thanks

**Comment by bonnaffe** [comment]
the error message says "No such file or directory", perhaps you should
check if this path exists on your machine ?
 /home/larbi/PFA/rootBuild/buildroot/output/build/linux-
592503752b6951972f161f04280683c5af38d173

2016-01-24 16:39 GMT+01:00 chfakht <notifications@github.com>:

**Comment by tpetazzoni** [comment]
This Github mirror is only a mirror of our official Git repository, and we don't take pull requests or issues on Github. Please use the Buildroot mailing list or bug tracker to report issues. Thanks!

**Comment by chfakht** [comment]
@bonnaffe No it doesn't exist ?

**Comment by bonnaffe** [comment]
@chfakht usually you'd want to specify a build directory.
$ make raspberry_defconfig O=build
$ cd build/
$ make
If it's not working for you, I'd recommend turning to buildroot.net, as Thomas suggested :)
