### ISSUE TITLE
Make use of rubygem optional

### ISSUE THREAD

**Issue by michelboaventura** [buildroot/buildroot#8]
Hi,

I'm working on a project on which I need rubygems installed on the host. Playing with ruby.mk I realize that it is always disabled. I'm wiling to make a PR changing it to be an option on menuconfig, but first I would like to know if you have interest on this PR. Thanks!

**Comment by tpetazzoni** [comment]
Thanks for your report. Unfortunately, the Github Buildroot repository is just a mirror of the official Git repository, and we don't take pull requests or handle issues on Github. Please use the Buildroot mailing list or bug tracker for such purposes. Thanks!

(Other than that, yes, improvements to the Ruby packaging are definitely welcome. See the Buildroot manual for details on how to contribute to Buildroot: we don't take PR, we want patch series submitted to the mailing list.)
